# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothulity', '0002_auto_20171128_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20)),
                ('notify_email', models.CharField(max_length=40)),
                ('max_ambig', models.IntegerField()),
                ('max_homop', models.IntegerField()),
                ('min_length', models.IntegerField()),
                ('max_length', models.IntegerField()),
                ('min_overlap', models.IntegerField()),
                ('screen_criteria', models.IntegerField()),
                ('chop_length', models.IntegerField()),
                ('precluster_diffs', models.IntegerField()),
                ('classify_seqs_cutoff', models.IntegerField()),
                ('amplicon_type', models.CharField(max_length=3)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothulity.JobID')),
            ],
        ),
    ]
