# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothulity', '0003_submissiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqsStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqs_count', models.IntegerField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothulity.JobID')),
            ],
        ),
    ]
