# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothulity', '0005_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='time_added',
            field=models.DateTimeField(null=True),
        ),
    ]
