# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mothulity', '0007_remove_jobstatus_time_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seqsstats',
            name='id',
        ),
        migrations.RemoveField(
            model_name='submissiondata',
            name='id',
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='retry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='slurm_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='submission time'),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='job_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mothulity.JobID'),
        ),
        migrations.AlterField(
            model_name='seqsstats',
            name='job_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mothulity.JobID'),
        ),
        migrations.AlterField(
            model_name='submissiondata',
            name='job_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mothulity.JobID'),
        ),
    ]
